// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-23iKbS-9IjoYy8IVrwDzwyIw3tAgBqI',
    appId: '1:623093370417:web:c2eef8322245a6693f8f10',
    messagingSenderId: '623093370417',
    projectId: 'chat-app-ad612',
    authDomain: 'chat-app-ad612.firebaseapp.com',
    storageBucket: 'chat-app-ad612.firebasestorage.app',
    measurementId: 'G-Z68194F6E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKClVakPnNY0n9ND20FqzwvK7gV69AJLI',
    appId: '1:623093370417:android:c49bf6441d161ed43f8f10',
    messagingSenderId: '623093370417',
    projectId: 'chat-app-ad612',
    storageBucket: 'chat-app-ad612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyT-UfzAhFZxloxJNgkPTnCP-BOOO-j-Y',
    appId: '1:623093370417:ios:cb9ee4cd2714a9cf3f8f10',
    messagingSenderId: '623093370417',
    projectId: 'chat-app-ad612',
    storageBucket: 'chat-app-ad612.firebasestorage.app',
    androidClientId: '623093370417-1hlusrl0ghcbahuia766nkti017dr68v.apps.googleusercontent.com',
    iosClientId: '623093370417-h9kptn7pftqrl06qqo6upoevrnm1kemr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyT-UfzAhFZxloxJNgkPTnCP-BOOO-j-Y',
    appId: '1:623093370417:ios:cb9ee4cd2714a9cf3f8f10',
    messagingSenderId: '623093370417',
    projectId: 'chat-app-ad612',
    storageBucket: 'chat-app-ad612.firebasestorage.app',
    androidClientId: '623093370417-1hlusrl0ghcbahuia766nkti017dr68v.apps.googleusercontent.com',
    iosClientId: '623093370417-h9kptn7pftqrl06qqo6upoevrnm1kemr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-23iKbS-9IjoYy8IVrwDzwyIw3tAgBqI',
    appId: '1:623093370417:web:a7889eabc4eca3f83f8f10',
    messagingSenderId: '623093370417',
    projectId: 'chat-app-ad612',
    authDomain: 'chat-app-ad612.firebaseapp.com',
    storageBucket: 'chat-app-ad612.firebasestorage.app',
    measurementId: 'G-NFF7QZXCN0',
  );

}